# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        survey:
            persistence:
                driver: orm
                model: App\Entity\Survey
                provider: ~
                listener: ~
                finder: ~
            properties:
                name:
                    type: text
                description:
                    type: text
                isActive:
                    type: boolean
